data:
  cifar_10_path: '/run/media/ybaa/Data/assignment/data/raw/cifar-10-python/'
  split_test:
    airplane: 0.2
    automobile: 0.2
    bird: 0.5
    cat: 0.2
    deer: 0.5
    dog: 0.2
    frog: 0.2
    horse: 0.2
    ship: 0.2
    truck: 0.5
  augmentation:
    horizontal_flip: 0.5
model:
  autoencoder: 
    tag: 'autoencoder_2'
    restore: True
    batch_size: 512
    epochs: 300
    initial_epoch: 0
    loss: 'mean_squared_error'
    optimizer: 'adam'
    ckpt_period_save: 50
  classifier:
    tag: '3_pretrained_2'
    restore: True
    batch_size: 512
    epochs: 50
    initial_epoch: 0
    loss: 'categorical_crossentropy'
    optimizer: 'adam'
    learning_rate: 0.0001
    ckpt_period_save: 10
    